

import type { TeamPerformanceRow } from "./types"
export const teamPerformanceData: TeamPerformanceRow[] = [
  {
    id: 1,
    fullName: "Pooja Bhaskar",
    projects: [
      { name: "Project Alpha" },
      { name: "Project Beta" },
    ],
    yetToStart: 5,
    inProgress: 10,
    completed: 18,
    totalHours: 210,
    efficiency: 92,
    status: "Active",
  },
  {
    id: 2,
    fullName: "Ethan Walker",
    projects: [{ name: "Project Alpha" }],
    yetToStart: 8,
    inProgress: 6,
    completed: 9,
    totalHours: 165,
    efficiency: 76,
    status: "Active",
  },
  {
    id: 3,
    fullName: "Olivia Hayes",
    projects: [
      { name: "Project Beta" },
      { name: "Project Gamma" },
      { name: "Project Delta" },
    ],
    yetToStart: 3,
    inProgress: 14,
    completed: 27,
    totalHours: 280,
    efficiency: 95,
    status: "Active",
  },
  {
    id: 4,
    fullName: "Rahul Verma",
    projects: [{ name: "Project Gamma" }],
    yetToStart: 12,
    inProgress: 4,
    completed: 6,
    totalHours: 120,
    efficiency: 64,
    status: "Inactive",
  },
  {
    id: 5,
    fullName: "Sophia Martinez",
    projects: [
      { name: "Project Alpha" },
      { name: "Project Delta" },
    ],
    yetToStart: 2,
    inProgress: 18,
    completed: 30,
    totalHours: 310,
    efficiency: 98,
    status: "Active",
  },
]
